name: glinet_connect
description: Flutter app for configuring GL.iNet router repeater WiFi credentials
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.5.0
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.0.0
  crypto: ^3.0.5
  crypt: ^4.3.0
  network_info_plus: ^6.1.1
  in_app_review: ^2.0.11
  connectivity_plus: ^7.0.0
  mobile_scanner: ^7.1.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true